---
- name: Include Debian family installation tasks
  ansible.builtin.include_tasks: apt/install.yml
  when: ansible_facts.os_family == 'Debian'

- name: Include generic installation tasks (Go-based)
  ansible.builtin.include_tasks: generic/install.yml
  when: ansible_facts.os_family != 'Debian'
